### ISSUE TITLE
didn't succeed to build

### ISSUE THREAD

**Issue by kylak** [thewh1teagle/sherpa-rs#1]
![image](https://github.com/thewh1teagle/sherpa-rs/assets/16438248/a8ed3a68-09b6-4b58-8d95-f23fb5eb22fc)

OS : Ubuntu 23.10
rustc version : 1.77.1
cargo version : 1.77.1

**Comment by thewh1teagle** [comment]
Hey @kylak 
Can you follow the instructions in [BUILDING.md](https://github.com/thewh1teagle/sherpa-rs/blob/main/BUILDING.md)
Specifically notice the Prerequisites

**Comment by kylak** [comment]
Thanks, the build worked.
However now, the running example doesn't work :
![image](https://github.com/thewh1teagle/sherpa-rs/assets/16438248/b3153cf1-cb35-4a21-9656-24b87b0d6da6)

**Comment by kylak** [comment]
Ok. It works, thanks.
