### ISSUE TITLE
Add support websocket ?

### ISSUE THREAD

**Issue by ghjdegithub** [thewh1teagle/sherpa-rs#14]

**Comment by thewh1teagle** [comment]
@ghjdegithub 

Hi,
sherpa-rs is direct bindings to the C API of sherpa-onnx
I think that the websocket is not related to the C API of sherpa-onnx. 
If you need websocket support, I recommend use the one provided by sherpa-onnx directly
See [sherpa/onnx/websocket/index.html](https://k2-fsa.github.io/sherpa/onnx/websocket/index.html)

**Comment by ghjdegithub** [comment]
I get it. It's a websocket implementation yourself, and then you can stream the data to the stream API.
