### ISSUE TITLE
How to set tts sid?

### ISSUE THREAD

**Issue by ghjdegithub** [thewh1teagle/sherpa-rs#15]

**Comment by ghjdegithub** [comment]
I find how to set tts sid.
[let audio = tts.generate(text, 0, speed).unwrap();](https://github.com/thewh1teagle/sherpa-rs/blob/49a0f2ce44b75ccdc39f2fde7cac02b62abe1337/examples/tts.rs#L82C1-L83C1)

**Comment by ghjdegithub** [comment]
update examples/tts.rs code.
Add running parameters(sid), It will help the user to know how the sid of tts is used.

**Comment by thewh1teagle** [comment]
@ghjdegithub 

See [examples/tts.rs](https://github.com/thewh1teagle/sherpa-rs/blob/main/examples/tts.rs)
You can pass `--sid`

**Comment by ghjdegithub** [comment]
Thanks. I see.
