### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by darxkies** [thewh1teagle/sherpa-rs#2]
https://github.com/thewh1teagle/sherpa-rs/blob/557cea20ec398f4eb1ab5d18280160f7ab1f0306/sys/build.rs#L91

**Comment by thewh1teagle** [comment]
Thanks! Fixed & releases pre release to crates.io

In addition I added build instructions with `cuda` in [BUILDING.md](https://github.com/thewh1teagle/sherpa-rs/blob/main/BUILDING.md)
Let me know if it worked for you :)

**Comment by darxkies** [comment]
Thank you for the fix. Unfortunately, there are still issues. It now fails with the following error:

error: could not find native static library `onnxruntime`, perhaps an -L flag is missing?

**Comment by thewh1teagle** [comment]
The issue was from upstream, and fixed in https://github.com/k2-fsa/sherpa-onnx/issues/1085
I also created Github actions to test cuda build in [actions/runs/9878944961](https://github.com/thewh1teagle/sherpa-rs/actions/runs/9878944961)

**Comment by darxkies** [comment]
It is not fixed yet. Right? I still get the error.

**Comment by thewh1teagle** [comment]
> It is not fixed yet. Right? I still get the error.

https://github.com/thewh1teagle/sherpa-rs/actions/runs/9913932528/job/27391980119

It's fixed in latest version
you can see successful build with cuda in github actions

**Comment by darxkies** [comment]
If I am not mistaken, CUDA is tested only on Windows. The entry for Ubuntu 22.04 does not build with CUDA turned on. 

I see only `cargo build` and no `cargo build --features="cuda"`. Using the latter command I get the onnxruntime missing error.

**Comment by darxkies** [comment]
I forgot to mention that I use Ubuntu 24.04.

**Comment by darxkies** [comment]
I just noticed that it does not compile in Windows either. The GitHub action silently failed with the same error message.

**Comment by thewh1teagle** [comment]
> I just noticed that it does not compile in Windows either. The GitHub action silently failed with the same error message.

You right. I missed that.
I released new version. the library is much more stable now and compiles successfully including with cuda.

https://github.com/thewh1teagle/sherpa-rs/actions/runs/10231498668/job/28307493397

**Comment by darxkies** [comment]
I'll take a look at it these days. Thank you.

**Comment by thewh1teagle** [comment]
I'll close this issue for now.
If you still experience issues with cuda feel free to reopen!
