### ISSUE TITLE
[Feature request]: Use pull-request for new commits

### ISSUE THREAD

**Issue by csukuangfj** [thewh1teagle/sherpa-rs#26]
I suggest that new commits be merged via pull request, not directly pushing them to the master branch.

Users watching this repo will get notified of new changes if a pull request is used. Also, it is easier to review
the changes and leave comments.

**Comment by thewh1teagle** [comment]
@csukuangfj 

Sometimes I push small changes straight to main. I'll try to make pull requests for any additions or fixes from now on.

**Comment by ghjdegithub** [comment]
> I suggest that new commits be merged via pull request, not directly pushing them to the master branch.我建议通过拉取请求合并新提交，而不是直接将它们推送到主分支。
> 
> Users watching this repo will get notified of new changes if a pull request is used. Also, it is easier to review如果使用拉取请求，观看此存储库的用户将收到新更改的通知。另外，审核也比较容易 the changes and leave comments.更改并留下评论。


> I suggest that new commits be merged via pull request, not directly pushing them to the master branch.我建议通过拉取请求合并新提交，而不是直接将它们推送到主分支。
> 
> Users watching this repo will get notified of new changes if a pull request is used. Also, it is easier to review如果使用拉取请求，观看此存储库的用户将收到新更改的通知。另外，审核也比较容易 the changes and leave comments.更改并留下评论。

你也要搞Rust吗？
