### ISSUE TITLE
Sometimes speech doesn't detected

### ISSUE THREAD

**Issue by altunenes** [thewh1teagle/sherpa-rs#3]
This crate is really nice! and I can confirm it works in Windows!! It is also interesting that it works faster and more efficiently than I expected.  thank you!

But sometimes (around %10 in a whole speech) it doesn't detect the speech as you are already aware 
https://github.com/k2-fsa/sherpa-onnx/issues/1084

note: may not related but sometimes ,when it doesn't detect, it  also gives this:

`sherpa-rs-sys-338fbbb2f5f9d19b\out\sherpa-onnx\sherpa-onnx\csrc\circular-buffer.cc:Push:96 Overflow! n: 512, size: 191872, n+size: 192384, capacity: 192000. Increase capacity to: 384000"
`

**Comment by thewh1teagle** [comment]
I think that I fixed both issues. now there's no overflow and the diarization works.
Can you try again the diarization example?

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/sherpa-onnx/pull/1099

It is fixed from the sherpa-onnx side.

Please refer to
https://github.com/k2-fsa/sherpa-onnx/blob/c2cc9dec5866e00a1464554f382668f2887de70c/python-api-examples/vad-remove-non-speech-segments-from-file.py#L108
for usage

```python3
    vad.flush()

    while not vad.empty():
        speech_samples.extend(vad.front.samples)
        vad.pop()
```

You need to call `flush()` at the end to detect the last segment.

**Comment by csukuangfj** [comment]
> I think that I fixed both issues. now there's no overflow and the diarization works.


By the way, don't be confused by the log `overflow`.
It is just a hint saying that your buffer size is too small. It will resize the buffer automatically without losing any data.

You can acutally disable the log by removing the statement that prints the log.
