### ISSUE TITLE
Change the project structure to workspace.

### ISSUE THREAD

**Issue by ghjdegithub** [thewh1teagle/sherpa-rs#30]
Project structure in workspace:
crates
  - sherpa-rs-sys
  - sherpa-rs
Cargo.toml

Wouldn't it be clearer to have a substructure like this.

**Comment by thewh1teagle** [comment]
@ghjdegithub
I think the current structure is already simple and, given the size of the project, it might not justify the additional effort for restructuring at this point.

Also, moving sherpa-rs into a subfolder could break the examples in the main folder, requiring us to declare each one manually in Cargo.toml - something the current setup handles automatically.
