### ISSUE TITLE
Multi-threading support

### ISSUE THREAD

**Issue by marchellodev** [thewh1teagle/sherpa-rs#34]
When I'm running the vad example (without diarization, just vad) on a two-core linux server, only one core is fully utilized.

Is it possible to make use of all available cores?

Thank you for such an awesome library!

**Comment by marchellodev** [comment]
When increasing `num_threads` to the number of cores system has utilization is higher, but still it is about 20% on average, not 100

**Comment by csukuangfj** [comment]
vad is super fast with a single thread. is there a reason to use multiple threads for vad?

**Comment by marchellodev** [comment]
@csukuangfj on a single thread (CPU) it takes way to much time to process a large audio (1.5 hours)

**Comment by thewh1teagle** [comment]
> on a single thread (CPU) it takes way to much time to process a large audio (1.5 hours)

How long it takes to diarize 1.5 hours?
I remember when I worked on [pyannote-rs](https://github.com/thewh1teagle/pyannote-rs) it took me ~2 minutes for one hour.

**Comment by marchellodev** [comment]
Nevermind this issue, `num_threads` works great! Thanks for such an awesome library!
